// Code generated by pogen. DO NOT EDIT.
package example

import "testing"

func TestPattern(t *testing.T) {
	type args struct {
		path string
	}
	tests := []struct {
		name        string
		args        args
		wantPattern string
		wantFound   bool
	}{
		{
			name: "users/userId",
			args: args{
				path: "/users/hogefuga",
			},
			wantPattern: "/users/{userId}",
			wantFound:   true,
		},
		{
			name: "alive",
			args: args{
				path: "/alive",
			},
			wantPattern: "/alive",
			wantFound:   true,
		},
		{
			name: "users/userId/no-user",
			args: args{
				path: "users/userId/no-user",
			},
			wantPattern: "",
			wantFound:   false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotPattern, gotFound := Pattern(tt.args.path)
			if gotPattern != tt.wantPattern {
				t.Errorf("Pattern() gotPattern = %v, want %v", gotPattern, tt.wantPattern)
			}
			if gotFound != tt.wantFound {
				t.Errorf("Pattern() gotFound = %v, want %v", gotFound, tt.wantFound)
			}
		})
	}
}
