// Code generated by pogen. DO NOT EDIT.
package example

import "testing"

func TestPattern(t *testing.T) {
	type args struct {
		path string
	}
	tests := []struct {
		name        string
		args        args
		wantPattern string
		wantFound   bool
	}{
		{
			name: "/alive",
			args: args{
				path: "/alive",
			},
			wantPattern: "/alive",
			wantFound:   true,
		},
		{
			name: "/users/{userId}",
			args: args{
				path: "/users/aA1_-",
			},
			wantPattern: "/users/{userId}",
			wantFound:   true,
		},
		{
			name: "/users/{userId}/nesteds",
			args: args{
				path: "/users/aA1_-/nesteds",
			},
			wantPattern: "/users/{userId}/nesteds",
			wantFound:   true,
		},
		{
			name: "/users/{userId}/nesteds/{nestedId}",
			args: args{
				path: "/users/aA1_-/nesteds/aA1_-",
			},
			wantPattern: "/users/{userId}/nesteds/{nestedId}",
			wantFound:   true,
		},
		{
			name: "nopass",
			args: args{
				path: "nopassnopass",
			},
			wantPattern: "",
			wantFound:   false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotPattern, gotFound := Pattern(tt.args.path)
			if gotPattern != tt.wantPattern {
				t.Errorf("Pattern() gotPattern = %v, want %v", gotPattern, tt.wantPattern)
			}
			if gotFound != tt.wantFound {
				t.Errorf("Pattern() gotFound = %v, want %v", gotFound, tt.wantFound)
			}
		})
	}
}
