// Code generated by pogen. DO NOT EDIT.
package example

import (
	"regexp"
)

// nolint
var pathToRegexp = map[string]*regexp.Regexp{
	"/alive":          regexp.MustCompile("^/alive$"),
	"/users/{userId}": regexp.MustCompile("^/users/[a-zA-Z0-9]*$"),
}

func Pattern(path string) (pattern string, found bool) {
	for k, v := range pathToRegexp {
		if v.MatchString(path) {
			return k, true
		}
	}
	return "", false
}
